### ISSUE TITLE
Select without search field?

### ISSUE THREAD

**Issue by dant00ine** [netguru/ember-select-guru#13]
Love your component. Is there any way to disable the search field? Trying to make a select input with just three options, and the search bar is unnecessary in this case.

**Comment by mamut** [comment]
Hmm I think you should be able to override the template for this component by creating a new one in `app/templates/components/ember-select-guru.hbs` in your application and then copying contents of https://github.com/netguru/ember-select-guru/blob/master/app/templates/components/ember-select-guru.hbs and removing the bit with the search field.

If you don't want to override it globally you can just create a new component that inherits from the main one (just like it happens here https://github.com/netguru/ember-select-guru/blob/master/app/components/ember-select-guru.js) and then change template of that new component.

There is no other mechanism to disable the search field in the addon at the moment.

Let me know if that works for you for the time being – glad this software is of use to you, cheers!

**Comment by dant00ine** [comment]
Mamut, thank you so much for the helpful response. A little confused about how to create a new component that inherits from the main one. I copied the entire component directory, renamed it, and changed the template code. Now I am looking at the value of export default in app/components/emeber-select-guru.js -- do I just change the name after export default to the one I intend to use for the extended component? Sorry, having problems with this because I am novice >.<

**Comment by mamut** [comment]
Hey there,

all you need to do to create a new component based on the original one is to create a file under `app/components/my-component.js` containing:

```js
import EmberSelectGuru from 'ember-select-guru/components/ember-select-guru';

export default EmberSelectGuru.extend({});
```

this new component will be available to you under `{{my-component}}` in your app – the important bit is the filename :) You need to give it a template too, which would live under `app/templates/components/my-component.hbs` – you can copy contents of https://github.com/netguru/ember-select-guru/blob/master/app/templates/components/ember-select-guru.hbs and modify that to your needs.

Hope it helps, cheers!

**Comment by dant00ine** [comment]
Mamut, just implemented today and it's fantastic. Thank you so much!
