### ISSUE TITLE
Had to manually copy ember-select-guru.css

### ISSUE THREAD

**Issue by bchan88** [netguru/ember-select-guru#3]
Hi!

First off I wanted to say that this is a wonderful component. Thanks for making it. My problem is that the css wasn't picked up until I copied ember-select-guru.css into vendor folder of my root project folder, and then added the following line to my ember-cli-build.js. 
```
app.import('vendor/ember-select-guru.css');
```
I was wondering if this is by design or I skipped another step after installing the component. Thanks!

**Comment by mamut** [comment]
Hey, thanks for letting us know – this should work out of the box, without you needing to add anything to your `ember-cli-build.js`. I'll take a look later today and try it out with a fresh project :)

**Comment by jniechcial** [comment]
@bchan88 Sorry for our late response. It's working right now without need to copying the css files.
