### ISSUE TITLE
Error: Could not find module...

### ISSUE THREAD

**Issue by Aaronfischer** [netguru/ember-select-guru#4]
When attempting to use:
```js
{{ember-select-guru
value=value
options=options
onSelect=(action "handleSelect")}}
```
An error is thrown: 
```
Uncaught Error: Could not find module `npm:lodash/array/intersection` imported from `[app-name]/components/ember-select-guru`
```

Perhaps I missed something in the initial setup/install? Current running:
* Ember 2.1.0
* Ember Data 2.1.0

**Comment by jniechcial** [comment]
Thanks @Aaronfischer! I'll handle it tomorrow and give you an update.

**Comment by jniechcial** [comment]
@Aaronfischer Thanks again for your input. I removed these dependencies and it doesn't need it now. Feel free to open any new issue if you find out anything broken ;)

**Comment by Aaronfischer** [comment]
Great, thanks @jniechcial!
