### ISSUE TITLE
CSS Overlap when multiple Select is used.

### ISSUE THREAD

**Issue by talhaobject90** [netguru/ember-select-guru#9]
When multiple ember-select-guru is used , The other select is seen through the drop down of the above one as in the pictures.. This might affect the over all reputation of the Select
![overlapp](https://cloud.githubusercontent.com/assets/7547924/11605866/ee8c6e9a-9b30-11e5-9826-fa6966dab982.png)

![overlapping-css](https://cloud.githubusercontent.com/assets/7547924/11605867/f5348278-9b30-11e5-8e00-9b4e70a6fe79.png)

**Comment by jniechcial** [comment]
Thanks a lot for another issue @talhaobject90. I just merged and updated version to 1.1.2 where it is fixed. We will eventually try to use ember-wormhole and better positioning, but for now simple z-index is doing its job.

Fixed in #11

**Comment by talhaobject90** [comment]
Thanks @jniechcial , I really enjoy this plugin.and that fix too.  ember-wormhole is a great stuff.. I hope you guys will make it awesome..
